#!/bin/bash

ROLE=$1;
ROLES_PATHS=(~/ansible/roles ~/adm/ansible/roles)

if [ -z "$ROLE" ]; then
    echo "What role documentation do you want?"
    exit 1
fi

for p in "${ROLES_PATHS[@]}"; do
    README=$p/$ROLE/README.md
    
    test -e $README && break
done

if [ ! -e $README ]; then
    echo "$ROLE: No such role"
    exit 1
fi

pandoc -s $README -t man -V title="Ansible Role" -V section=7 | man -l -
